name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - CA-Demo
  pull_request:
    branches:
      - CA-Demo

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build Docker image (tag with both commit SHA and latest)
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ca-app
          VERSION=v${{ github.run_number }}
          IMAGE_TAG=${{ github.sha }}

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Build and tag two versions: commit SHA and latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .

      # 4. Push Docker images
      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION

      # 5. Cleanup local Docker images
      - name: Cleanup local Docker images
        run: |
          docker rmi -f $IMAGE_NAME:$IMAGE_TAG || true
          docker rmi -f $IMAGE_NAME:latest || true

      # 6. Retain only last 5 images
      - name: Prune GHCR (keep last 5 images)
        uses: actions/delete-package-versions@v5
        with:
          package-name: "ca-app"
          package-type: "container"
          min-versions-to-keep: 5

      # 7. Rollback on failure
      - name: Rollback on failure
        if: failure()
        run: |
          echo "Build/Push failed — restoring previous Docker image"
          # Example rollback logic (adjust to your deploy process):
          # docker pull ghcr.io/${{ github.repository_owner }}/ca-app:previous
