name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - CA-Demo
  pull_request:
    branches:
      - CA-Demo

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.vars.outputs.image_name }}
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - name: Set image variables
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ca-app
          IMAGE_TAG=${{ github.sha }}
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.image_tag }} \
            -t ${{ needs.prepare.outputs.image_name }}:latest .

  push:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.image_tag }}
          docker push ${{ needs.prepare.outputs.image_name }}:latest
